import type { Metadata } from 'next'

import { Header } from '@/layers/widgets/header'

import './globals.scss'

export const metadata: Metadata = {
	title: 'GameHosting Reboot',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="ru">
			<body>
				<Header />
				{children}
			</body>
		</html>
	)
}
